### ISSUE TITLE
Refactor OpenAPI Class to Separate Factory Logic from Object Logic

### ISSUE THREAD

**Issue by sternakt** [airtai/fastagency#416]
The current implementation of the `OpenAPI` class contains a problem where the `__init__` method allows setting the server and title, but the subsequent call to the `create` method, which is a class method, does not correctly preserve these attributes in the returned `OpenAPI` object. This leads to inconsistencies when trying to use the created object.

### Problem Description

The `OpenAPI` class's `__init__` method initializes the object with servers and a title:

```python
class OpenAPI:
    def __init__(
        self, servers: list[dict[str, Any]], title: Optional[str] = None, **kwargs: Any
    ) -> None:
        """Proxy class to generate client from OpenAPI schema."""
        self.servers = servers
        self.title = title
        ...
```

However, when the `create` method is called, it generates a new `OpenAPI` object without retaining the server and title attributes:

```python
@classmethod
def create(
    cls,
    openapi_json: Optional[str] = None,
    openapi_url: Optional[str] = None,
    client_source_path: Optional[str] = None,
) -> "OpenAPI":
    ...
    client: OpenAPI = main.app  # type: ignore [attr-defined]
    client.set_globals(main, suffix)
    return client
```

### Proposed Solution

1. **Separate Factory Logic from Object Logic**: Refactor the class to distinguish between the creation of the `OpenAPI` object and its initialization. Consider using a separate factory function or class method to create instances without mixing in the initialization logic.

2. **Ensure Attributes are Preserved**: Modify the object creation logic to ensure that the `servers` and `title` are set correctly when creating a new instance of `OpenAPI`.

3. **Update Class Structure**: This refactoring can enhance the clarity and maintainability of the code. For example, you could introduce a `create_openapi` factory function:

```python
def create_openapi(
    servers: list[dict[str, Any]],
    title: Optional[str] = None,
    openapi_json: Optional[str] = None,
    openapi_url: Optional[str] = None,
    client_source_path: Optional[str] = None,
) -> OpenAPI:
    openapi_instance = OpenAPI(servers=servers, title=title)
    # Load the OpenAPI schema from the given source and initialize further
    ...
    return openapi_instance
```

### Tasks:
- [ ] Refactor the `OpenAPI` class to separate the factory logic from the instance initialization logic.
- [ ] Ensure that the `create` method or equivalent preserves the `servers` and `title` attributes correctly.
- [ ] Update any related documentation to reflect changes in the class structure and usage.
